/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRulesRouteImport } from './routes/_app.rules'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as AppLaunchRouteImport } from './routes/_app.launch'
import { Route as AppFundRouteImport } from './routes/_app.fund'
import { Route as AppAgentRouteImport } from './routes/_app.agent'
import { Route as AppActivityRouteImport } from './routes/_app.activity'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchRoute = AppLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AppRoute,
} as any)
const AppFundRoute = AppFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/activity': typeof AppActivityRoute
  '/agent': typeof AppAgentRoute
  '/fund': typeof AppFundRoute
  '/launch': typeof AppLaunchRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/profile': typeof AppProfileRoute
  '/rules': typeof AppRulesRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/activity': typeof AppActivityRoute
  '/agent': typeof AppAgentRoute
  '/fund': typeof AppFundRoute
  '/launch': typeof AppLaunchRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/profile': typeof AppProfileRoute
  '/rules': typeof AppRulesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/fund': typeof AppFundRoute
  '/_app/launch': typeof AppLaunchRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/onboarding'
    | '/activity'
    | '/agent'
    | '/fund'
    | '/launch'
    | '/marketplace'
    | '/profile'
    | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/onboarding'
    | '/activity'
    | '/agent'
    | '/fund'
    | '/launch'
    | '/marketplace'
    | '/profile'
    | '/rules'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/landing'
    | '/onboarding'
    | '/_app/activity'
    | '/_app/agent'
    | '/_app/fund'
    | '/_app/launch'
    | '/_app/marketplace'
    | '/_app/profile'
    | '/_app/rules'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/launch': {
      id: '/_app/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof AppLaunchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund': {
      id: '/_app/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AppFundRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAgentRoute: typeof AppAgentRoute
  AppFundRoute: typeof AppFundRoute
  AppLaunchRoute: typeof AppLaunchRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRulesRoute: typeof AppRulesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAgentRoute: AppAgentRoute,
  AppFundRoute: AppFundRoute,
  AppLaunchRoute: AppLaunchRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppProfileRoute: AppProfileRoute,
  AppRulesRoute: AppRulesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
